version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: alexlondging
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
