export const ROOM_LIST_REQUEST = 'ROOM_LIST_REQUEST'
export const ROOM_LIST_SUCCESS = 'ROOM_LIST_SUCCESS'
export const ROOM_LIST_FAIL = 'ROOM_LIST_FAIL'

export const ROOM_ADMIN_LIST_REQUEST = 'ROOM_ADMIN_LIST_REQUEST'
export const ROOM_ADMIN_LIST_SUCCESS = 'ROOM_ADMIN_LIST_SUCCESS'
export const ROOM_ADMIN_LIST_FAIL = 'ROOM_ADMIN_LIST_FAIL'

export const ROOM_DETAILS_REQUEST = 'ROOM_DETAILS_REQUEST'
export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL'
export const ROOM_DETAILS_RESET = 'ROOM_DETAILS_RESET'
